const number1 = 3;
const number2 = 6;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 25;
const payment = 5;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const test = 45;
const assignment = 67;
const final = 89;
const grade = (test + assignment + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = ' Eduardo ';
const lastName = ' Gallegos ';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const ph = 35;
const isAcidic = ph < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numerberOfSoldiers = 256;
const isSparta = numerberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
const nickname = fullName + 'is the GOAT';
console.log(nickname);
console.log(typeof nickname);
